# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SxIXW5pZl_rukYqF1zeC3Bzz_la4BxSM
"""

import random

def taxmin_oyin():
    print("Sonni Taxmin Qilish O'yiniga Xush Kelibsiz!")
    print("1 dan 100 gacha son tanladim. Uni topishga harakat qiling.")

    tasodifiy_son = random.randint(1, 100)
    taxminlar_soni = 0

    while True:
        try:
            foydalanuvchi_soni = int(input("Son kiriting: "))
            taxminlar_soni += 1

            if foydalanuvchi_soni < tasodifiy_son:
                print("Mening sonim bundan kattaroq! Qayta urinib ko'ring.")
            elif foydalanuvchi_soni > tasodifiy_son:
                print("Mening sonim bundan kichikroq! Qayta urinib ko'ring.")
            else:
                print(f"Tabriklaymiz! Siz {taxminlar_soni} ta urinishda to'g'ri topdingiz.")
                break
        except ValueError:
            print("Faqat butun son kiriting!")

# O'yinni boshlash
taxmin_oyin()